### ISSUE TITLE
TypeError: channel.fetchMessages is not a function

### ISSUE THREAD

**Issue by slice** [devsnek/retrocord#23]
I'm interested in using retrocord as an alternative client for use in the situation of abusive electron-crashing raiding which naturally necessitates usage of an alternative client. I found this bug while trying to `/join` a guild:

![image](https://user-images.githubusercontent.com/4206232/34459284-d5ed1474-eda0-11e7-9e37-e0ae4d96cc41.png)

Sorry for the screenshot, I can't copy paste due to the usage of special terminal features.

**Comment by apheen** [comment]
I'm also getting a 'TypeError: channel.fetchMessages is not a function' error when attempting join a server channel or dm.

**Comment by apheen** [comment]
> Unhandled Error (You should report this)                                                                                                                                                         
TypeError: channel.fetchMessages is not a function                                                                                                                                               
    at Object.run (C:\Users\apheen\AppData\Roaming\npm\node_modules\retrocord\src\commands.js:66:15)                                                                                             
    at GUI.gui.on (C:\Users\apheen\AppData\Roaming\npm\node_modules\retrocord\src\index.js:32:48)                                                                                                
    at emitOne (events.js:116:13)                                                                                                                                                                
    at GUI.emit (events.js:211:7)                                                                                                                                                                
    at Textbox.inputbox.key (C:\Users\apheen\AppData\Roaming\npm\node_modules\retrocord\src\gui.js:42:17)                                                                                        
    at Textbox.EventEmitter._emit (C:\Users\apheen\AppData\Roaming\npm\node_modules\retrocord\node_modules\blessed\lib\events.js:94:20)                                                          
    at Textbox.EventEmitter.emit (C:\Users\apheen\AppData\Roaming\npm\node_modules\retrocord\node_modules\blessed\lib\events.js:117:12)                                                          
    at Program.<anonymous> (C:\Users\apheen\AppData\Roaming\npm\node_modules\retrocord\node_modules\blessed\lib\widgets\screen.js:603:15)                                                        
    at emitTwo (events.js:126:13)                                                                                                                                                                
    at Program.emit (events.js:214:7)                                                                                                                                                            
 -- End Error --
